name: "Install native dependencies on Ubuntu"
description: "Install native dependencies on Ubuntu"
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y pkg-config libicu-dev libvips-dev libmagic-dev
